### ISSUE TITLE
Combine all equipment of a bay in one container

### ISSUE THREAD

**Issue by dlabordus** [com-pas/compas-scl-auto-alignment#39]
As a engineer 
I want all equipment of a bay to be grouped
So that it is easier to see what's in a bay and also to move

Currently it's not possible to group all equipment of a bay together.
All equipment is grouped on the voltage level. 
This can cause in some situations that equipment of 1 bay is spread over the busbar.

**Comment by dlabordus** [comment]
![image](https://user-images.githubusercontent.com/1453032/149341720-df02b168-f90e-4617-825e-43a0e40d9001.png)

**Comment by dlabordus** [comment]
file:///home/dlabordus/Downloads/scl/TrainingIEC61850_auto.scd

**Comment by BenoitJeanson** [comment]
Great picture!
I see. That is not a problem of the CellDectector. Is we would develop a specific one, that would not change as actually the definition of a cell would necessary imply these two clusters to be 2 "cells".
If you want to group them, today the only option is at the level of the positionner and use PositionFromExtension rather than PositionByClustering... (see last update of the PoC, in which the order is defined by syx data). But that is a bit demanding as you have to give much more information. I will try an update on the example to show you we could reach something you expect. But, probably, we should design a new grouping concept ("bay")... I will think of it...

**Comment by BenoitJeanson** [comment]
I updated the [PoC](https://github.com/BenoitJeanson/compasSLDExample)  for the semi-automatic positioning.
![test_ExplicitPosition_stacked](https://user-images.githubusercontent.com/39792051/151137773-ec6c7609-43b7-4855-a4bb-44e587d8a3d0.svg)

**Comment by Sander3003** [comment]
@dlabordus can we incorporate this improvement in CoMPAS?
